version: '3.8'

services:
  api:
    image: strhzy/eldomvideoapi:dev
    build: .
      #context: . 
      #dockerfile: Dockerfile  
    ports:
      - "8080:8080"
    restart:
      always
  db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart:
      always
volumes:
  pgdata:
