name: Deploy API

on:
  push:
    branches:
      - master

jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .  # Путь к контексту
          file: ./EldoMvideoAPI/Dockerfile  # Укажите путь к Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eldomvideoapi:latest

  run-docker:
    needs: push-docker
    runs-on: self-hosted
    steps:
      - name: Get docker-compose
        run: sudo curl -OJ https://raw.githubusercontent.com/strhzy/CoolAPI/refs/heads/master/EldoMvideoAPI/docker-compose.yml
        
      - name: Down old docker
        run: sudo docker-compose down

      - name: Clear unused dockers
        run: sudo docker system prune -f
      
      - name: Run docker-compose
        run: sudo docker-compose up -d
