name: Deploy API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🔑 Подключение к серверу и деплой
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ "147.45.196.64" }}
          username: ${{ "root" }}
          key: ${{ "-----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACBYgDr6BPKurUI7Sg/mzl+uuIjPGM+UXmO/9+HGUkx20AAAAKCIhHaliIR2pQAAAAtzc2gtZWQyNTUxOQAAACBYgDr6BPKurUI7Sg/mzl+uuIjPGM+UXmO/9+HGUkx20AAAAEBMBa2WxshUrvwZThAHPVu62tuE77Q7qjBfIfDNIR2TgViAOvoE8q6tQjtKD+bOX664iM8Yz5ReY7/34cZSTHbQAAAAFnN0cmh6eUBERVNLVE9QLTJTVEhOVUwBAgMEBQYH-----END OPENSSH PRIVATE KEY-----" }}
          script: |
            cd /root/CoolAPI/EldoMvideoAPI
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            docker system prune -f
