name: Deploy API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🔑 Подключение к серверу и деплой
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}  # Убрал лишние кавычки
          username: ${{ secrets.SERVER_USER }}  # Убрал лишние кавычки
          key: ${{ secrets.SERVER_SSH_KEY }}          
          script: |
            cd /home/strhzy/CoolAPI/EldoMvideoAPI
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            docker system prune -f
