name: Deploy API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔑 Подключение к серверу
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/strhzy/
            git clone https://github.com/strhzy/CoolAPI.git .
            cd /home/strhzy/CoolAPI
            git pull origin master
            cd /home/strhzy/CoolAPI/EldoMvideoAPI
            docker-compose down
            docker-compose up -d --build
            docker system prune -f

